export const LEFT_SIDE = [
  [
    {
      symbol: 'H',
      name: 'Hydrogen',
      number: 1,
      atomic_mass: 1.008,
      category: 'nonmetal',
      electron_configuration: '1s1',
    },
    {
      symbol: 'Li',
      name: 'Lithium',
      number: 3,
      atomic_mass: 6.94,
      category: 'alkali-metal',
      electron_configuration: '[He] 2s1',
    },
    {
      symbol: 'Na',
      name: 'Sodium',
      number: 11,
      atomic_mass: 22.99,
      category: 'alkali-metal',
      electron_configuration: '[Ne] 3s1',
    },
    {
      symbol: 'K',
      name: 'Potassium',
      number: 19,
      atomic_mass: 39.098,
      category: 'alkali-metal',
      electron_configuration: '[Ar] 4s1',
    },
    {
      symbol: 'Rb',
      name: 'Rubidium',
      number: 37,
      atomic_mass: 85.468,
      category: 'alkali-metal',
      electron_configuration: '[Kr] 5s1',
    },
    {
      symbol: 'Cs',
      name: 'Cesium',
      number: 55,
      atomic_mass: 132.905,
      category: 'alkali-metal',
      electron_configuration: '[Xe] 6s1',
    },
    {
      symbol: 'Fr',
      name: 'Francium',
      number: 87,
      atomic_mass: 223,
      category: 'alkali-metal',
      electron_configuration: '[Rn] 7s1',
    },
  ],
  [
    {
      symbol: 'Be',
      name: 'Beryllium',
      number: 4,
      atomic_mass: 9.0122,
      category: 'alkaline-earth-metal',
      electron_configuration: '[He] 2s2',
    },
    {
      symbol: 'Mg',
      name: 'Magnesium',
      number: 12,
      atomic_mass: 24.305,
      category: 'alkaline-earth-metal',
      electron_configuration: '[Ne] 3s2',
    },
    {
      symbol: 'Ca',
      name: 'Calcium',
      number: 20,
      atomic_mass: 40.078,
      category: 'alkaline-earth-metal',
      electron_configuration: '[Ar] 4s2',
    },
    {
      symbol: 'Sr',
      name: 'Strontium',
      number: 38,
      atomic_mass: 87.62,
      category: 'alkaline-earth-metal',
      electron_configuration: '[Kr] 5s2',
    },
    {
      symbol: 'Ba',
      name: 'Barium',
      number: 56,
      atomic_mass: 137.327,
      category: 'alkaline-earth-metal',
      electron_configuration: '[Xe] 6s2',
    },
    {
      symbol: 'Ra',
      name: 'Radium',
      number: 88,
      atomic_mass: 226,
      category: 'alkaline-earth-metal',
      electron_configuration: '[Rn] 7s2',
    },
  ],
  [
    {
      symbol: 'Sc',
      name: 'Scandium',
      number: 21,
      atomic_mass: 44.956,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d1 4s2',
    },
    {
      symbol: 'Y',
      name: 'Yttrium',
      number: 39,
      atomic_mass: 88.906,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d1 5s2',
    },
    {
      symbol: 'La',
      name: 'Lanthanum',
      number: 57,
      atomic_mass: 138.91,
      category: 'lanthanide',
      electron_configuration: '[Xe] 5d1 6s2',
    },
    {
      symbol: 'Ac',
      name: 'Actinium',
      number: 89,
      atomic_mass: 227,
      category: 'actinide',
      electron_configuration: '[Rn] 6d1 7s2',
    },
  ],
];

export const RIGHT_SIDE = [
  [
    {
      symbol: 'Ti',
      name: 'Titanium',
      number: 22,
      atomic_mass: 47.867,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d2 4s2',
    },
    {
      symbol: 'Zr',
      name: 'Zirconium',
      number: 40,
      atomic_mass: 91.224,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d2 5s2',
    },
    {
      symbol: 'Hf',
      name: 'Hafnium',
      number: 72,
      atomic_mass: 178.49,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d2 6s2',
    },
    {
      symbol: 'Rf',
      name: 'Rutherfordium',
      number: 104,
      atomic_mass: 267,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d2 7s2',
    },
  ],
  [
    {
      symbol: 'V',
      name: 'Vanadium',
      number: 23,
      atomic_mass: 50.942,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d3 4s2',
    },
    {
      symbol: 'Nb',
      name: 'Niobium',
      number: 41,
      atomic_mass: 92.906,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d4 5s1',
    },
    {
      symbol: 'Ta',
      name: 'Tantalum',
      number: 73,
      atomic_mass: 180.947,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d3 6s2',
    },
    {
      symbol: 'Db',
      name: 'Dubnium',
      number: 105,
      atomic_mass: 268,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d3 7s2',
    },
  ],
  [
    {
      symbol: 'Cr',
      name: 'Chromium',
      number: 24,
      atomic_mass: 51.996,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d5 4s1',
    },
    {
      symbol: 'Mo',
      name: 'Molybdenum',
      number: 42,
      atomic_mass: 95.95,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d5 5s1',
    },
    {
      symbol: 'W',
      name: 'Tungsten',
      number: 74,
      atomic_mass: 183.84,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d4 6s2',
    },
    {
      symbol: 'Sg',
      name: 'Seaborgium',
      number: 106,
      atomic_mass: 269,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d4 7s2',
    },
  ],
  [
    {
      symbol: 'Mn',
      name: 'Manganese',
      number: 25,
      atomic_mass: 54.938,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d5 4s2',
    },
    {
      symbol: 'Tc',
      name: 'Technetium',
      number: 43,
      atomic_mass: 98,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d5 5s2',
    },
    {
      symbol: 'Re',
      name: 'Rhenium',
      number: 75,
      atomic_mass: 186.207,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d5 6s2',
    },
    {
      symbol: 'Bh',
      name: 'Bohrium',
      number: 107,
      atomic_mass: 270,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d5 7s2',
    },
  ],
  [
    {
      symbol: 'Fe',
      name: 'Iron',
      number: 26,
      atomic_mass: 55.845,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d6 4s2',
    },
    {
      symbol: 'Ru',
      name: 'Ruthenium',
      number: 44,
      atomic_mass: 101.07,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d7 5s1',
    },
    {
      symbol: 'Os',
      name: 'Osmium',
      number: 76,
      atomic_mass: 190.23,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d6 6s2',
    },
    {
      symbol: 'Hs',
      name: 'Hassium',
      number: 108,
      atomic_mass: 277,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d6 7s2',
    },
  ],
  [
    {
      symbol: 'Co',
      name: 'Cobalt',
      number: 27,
      atomic_mass: 58.933,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d7 4s2',
    },
    {
      symbol: 'Rh',
      name: 'Rhodium',
      number: 45,
      atomic_mass: 102.91,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d8 5s1',
    },
    {
      symbol: 'Ir',
      name: 'Iridium',
      number: 77,
      atomic_mass: 192.22,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d7 6s2',
    },
    {
      symbol: 'Mt',
      name: 'Meitnerium',
      number: 109,
      atomic_mass: 278,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d7 7s2',
    },
  ],
  [
    {
      symbol: 'Ni',
      name: 'Nickel',
      number: 28,
      atomic_mass: 58.693,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d8 4s2',
    },
    {
      symbol: 'Pd',
      name: 'Palladium',
      number: 46,
      atomic_mass: 106.42,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d10',
    },
    {
      symbol: 'Pt',
      name: 'Platinum',
      number: 78,
      atomic_mass: 195.08,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d9 6s1',
    },
    {
      symbol: 'Ds',
      name: 'Darmstadtium',
      number: 110,
      atomic_mass: 281,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d9 7s1',
    },
  ],
  [
    {
      symbol: 'Cu',
      name: 'Copper',
      number: 29,
      atomic_mass: 63.546,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d10 4s1',
    },
    {
      symbol: 'Ag',
      name: 'Silver',
      number: 47,
      atomic_mass: 107.87,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d10 5s1',
    },
    {
      symbol: 'Au',
      name: 'Gold',
      number: 79,
      atomic_mass: 196.97,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d10 6s1',
    },
    {
      symbol: 'Rg',
      name: 'Roentgenium',
      number: 111,
      atomic_mass: 281,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d10 7s1',
    },
  ],
  [
    {
      symbol: 'Zn',
      name: 'Zinc',
      number: 30,
      atomic_mass: 65.38,
      category: 'transition-metal',
      electron_configuration: '[Ar] 3d10 4s2',
    },
    {
      symbol: 'Cd',
      name: 'Cadmium',
      number: 48,
      atomic_mass: 112.41,
      category: 'transition-metal',
      electron_configuration: '[Kr] 4d10 5s2',
    },
    {
      symbol: 'Hg',
      name: 'Mercury',
      number: 80,
      atomic_mass: 200.59,
      category: 'transition-metal',
      electron_configuration: '[Xe] 4f14 5d10 6s2',
    },
    {
      symbol: 'Cn',
      name: 'Copernicium',
      number: 112,
      atomic_mass: 285,
      category: 'transition-metal',
      electron_configuration: '[Rn] 5f14 6d10 7s2',
    },
  ],
  [
    {
      symbol: 'B',
      name: 'Boron',
      number: 5,
      atomic_mass: 10.81,
      category: 'metalloid',
      electron_configuration: '[He] 2s2 2p1',
    },
    {
      symbol: 'Al',
      name: 'Aluminum',
      number: 13,
      atomic_mass: 26.982,
      category: 'post-transition-metal',
      electron_configuration: '[Ne] 3s2 3p1',
    },
    {
      symbol: 'Ga',
      name: 'Gallium',
      number: 31,
      atomic_mass: 69.723,
      category: 'post-transition-metal',
      electron_configuration: '[Ar] 3d10 4s2 4p1',
    },
    {
      symbol: 'In',
      name: 'Indium',
      number: 49,
      atomic_mass: 114.818,
      category: 'post-transition-metal',
      electron_configuration: '[Kr] 4d10 5s2 5p1',
    },
    {
      symbol: 'Tl',
      name: 'Thallium',
      number: 81,
      atomic_mass: 204.38,
      category: 'post-transition-metal',
      electron_configuration: '[Xe] 4f14 5d10 6s2 6p1',
    },
    {
      symbol: 'Nh',
      name: 'Nihonium',
      number: 113,
      atomic_mass: 286,
      category: 'post-transition-metal',
      electron_configuration: '[Rn] 5f14 6d10 7s2 7p1',
    },
  ],
  [
    {
      symbol: 'C',
      name: 'Carbon',
      number: 6,
      atomic_mass: 12.011,
      category: 'nonmetal',
      electron_configuration: '[He] 2s2 2p2',
    },
    {
      symbol: 'Si',
      name: 'Silicon',
      number: 14,
      atomic_mass: 28.085,
      category: 'metalloid',
      electron_configuration: '[Ne] 3s2 3p2',
    },
    {
      symbol: 'Ge',
      name: 'Germanium',
      number: 32,
      atomic_mass: 72.63,
      category: 'metalloid',
      electron_configuration: '[Ar] 3d10 4s2 4p2',
    },
    {
      symbol: 'Sn',
      name: 'Tin',
      number: 50,
      atomic_mass: 118.71,
      category: 'post-transition-metal',
      electron_configuration: '[Kr] 4d10 5s2 5p2',
    },
    {
      symbol: 'Pb',
      name: 'Lead',
      number: 82,
      atomic_mass: 207.2,
      category: 'post-transition-metal',
      electron_configuration: '[Xe] 4f14 5d10 6s2 6p2',
    },
    {
      symbol: 'Fl',
      name: 'Flerovium',
      number: 114,
      atomic_mass: 289,
      category: 'post-transition-metal',
      electron_configuration: '[Rn] 5f14 6d10 7s2 7p2',
    },
  ],
  [
    {
      symbol: 'N',
      name: 'Nitrogen',
      number: 7,
      atomic_mass: 14.007,
      category: 'nonmetal',
      electron_configuration: '[He] 2s2 2p3',
    },
    {
      symbol: 'P',
      name: 'Phosphorus',
      number: 15,
      atomic_mass: 30.974,
      category: 'nonmetal',
      electron_configuration: '[Ne] 3s2 3p3',
    },
    {
      symbol: 'As',
      name: 'Arsenic',
      number: 33,
      atomic_mass: 74.922,
      category: 'metalloid',
      electron_configuration: '[Ar] 3d10 4s2 4p3',
    },
    {
      symbol: 'Sb',
      name: 'Antimony',
      number: 51,
      atomic_mass: 121.76,
      category: 'metalloid',
      electron_configuration: '[Kr] 4d10 5s2 5p3',
    },
    {
      symbol: 'Bi',
      name: 'Bismuth',
      number: 83,
      atomic_mass: 208.98,
      category: 'post-transition-metal',
      electron_configuration: '[Xe] 4f14 5d10 6s2 6p3',
    },
    {
      symbol: 'Mc',
      name: 'Moscovium',
      number: 115,
      atomic_mass: 290,
      category: 'post-transition-metal',
      electron_configuration: '[Rn] 5f14 6d10 7s2 7p3',
    },
  ],
  [
    {
      symbol: 'O',
      name: 'Oxygen',
      number: 8,
      atomic_mass: 15.999,
      category: 'nonmetal',
      electron_configuration: '[He] 2s2 2p4',
    },
    {
      symbol: 'S',
      name: 'Sulfur',
      number: 16,
      atomic_mass: 32.06,
      category: 'nonmetal',
      electron_configuration: '[Ne] 3s2 3p4',
    },
    {
      symbol: 'Se',
      name: 'Selenium',
      number: 34,
      atomic_mass: 78.971,
      category: 'nonmetal',
      electron_configuration: '[Ar] 3d10 4s2 4p4',
    },
    {
      symbol: 'Te',
      name: 'Tellurium',
      number: 52,
      atomic_mass: 127.6,
      category: 'metalloid',
      electron_configuration: '[Kr] 4d10 5s2 5p4',
    },
    {
      symbol: 'Po',
      name: 'Polonium',
      number: 84,
      atomic_mass: 209,
      category: 'metalloid',
      electron_configuration: '[Xe] 4f14 5d10 6s2 6p4',
    },
    {
      symbol: 'Lv',
      name: 'Livermorium',
      number: 116,
      atomic_mass: 293,
      category: 'post-transition-metal',
      electron_configuration: '[Rn] 5f14 6d10 7s2 7p4',
    },
  ],
  [
    {
      symbol: 'F',
      name: 'Fluorine',
      number: 9,
      atomic_mass: 18.998,
      category: 'halogen',
      electron_configuration: '[He] 2s2 2p5',
    },
    {
      symbol: 'Cl',
      name: 'Chlorine',
      number: 17,
      atomic_mass: 35.45,
      category: 'halogen',
      electron_configuration: '[Ne] 3s2 3p5',
    },
    {
      symbol: 'Br',
      name: 'Bromine',
      number: 35,
      atomic_mass: 79.904,
      category: 'halogen',
      electron_configuration: '[Ar] 3d10 4s2 4p5',
    },
    {
      symbol: 'I',
      name: 'Iodine',
      number: 53,
      atomic_mass: 126.9,
      category: 'halogen',
      electron_configuration: '[Kr] 4d10 5s2 5p5',
    },
    {
      symbol: 'At',
      name: 'Astatine',
      number: 85,
      atomic_mass: 210,
      category: 'halogen',
      electron_configuration: '[Xe] 4f14 5d10 6s2 6p5',
    },
    {
      symbol: 'Ts',
      name: 'Tennessine',
      number: 117,
      atomic_mass: 294,
      category: 'halogen',
      electron_configuration: '[Rn] 5f14 6d10 7s2 7p5',
    },
  ],
  [
    {
      symbol: 'He',
      name: 'Helium',
      number: 2,
      atomic_mass: 4.0026,
      category: 'noble-gas',
      electron_configuration: '1s2',
    },
    {
      symbol: 'Ne',
      name: 'Neon',
      number: 10,
      atomic_mass: 20.18,
      category: 'noble-gas',
      electron_configuration: '[He] 2s2 2p6',
    },
    {
      symbol: 'Ar',
      name: 'Argon',
      number: 18,
      atomic_mass: 39.948,
      category: 'noble-gas',
      electron_configuration: '[Ne] 3s2 3p6',
    },
    {
      symbol: 'Kr',
      name: 'Krypton',
      number: 36,
      atomic_mass: 83.798,
      category: 'noble-gas',
      electron_configuration: '[Ar] 3d10 4s2 4p6',
    },
    {
      symbol: 'Xe',
      name: 'Xenon',
      number: 54,
      atomic_mass: 131.293,
      category: 'noble-gas',
      electron_configuration: '[Kr] 4d10 5s2 5p6',
    },
    {
      symbol: 'Rn',
      name: 'Radon',
      number: 86,
      atomic_mass: 222,
      category: 'noble-gas',
      electron_configuration: '[Xe] 4f14 5d10 6s2 6p6',
    },
    {
      symbol: 'Og',
      name: 'Oganesson',
      number: 118,
      atomic_mass: 294,
      category: 'noble-gas',
      electron_configuration: '[Rn] 5f14 6d10 7s2 7p6',
    },
  ],
];

export const BOTTOM = [
  [
    {
      symbol: 'Ce',
      name: 'Cerium',
      number: 58,
      atomic_mass: 140.12,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f1 5d1 6s2',
    },
    {
      symbol: 'Pr',
      name: 'Praseodymium',
      number: 59,
      atomic_mass: 140.91,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f3 6s2',
    },
    {
      symbol: 'Nd',
      name: 'Neodymium',
      number: 60,
      atomic_mass: 144.24,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f4 6s2',
    },
    {
      symbol: 'Pm',
      name: 'Promethium',
      number: 61,
      atomic_mass: 145,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f5 6s2',
    },
    {
      symbol: 'Sm',
      name: 'Samarium',
      number: 62,
      atomic_mass: 150.36,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f6 6s2',
    },
    {
      symbol: 'Eu',
      name: 'Europium',
      number: 63,
      atomic_mass: 151.96,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f7 6s2',
    },
    {
      symbol: 'Gd',
      name: 'Gadolinium',
      number: 64,
      atomic_mass: 157.25,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f7 5d1 6s2',
    },
    {
      symbol: 'Tb',
      name: 'Terbium',
      number: 65,
      atomic_mass: 158.93,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f9 6s2',
    },
    {
      symbol: 'Dy',
      name: 'Dysprosium',
      number: 66,
      atomic_mass: 162.5,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f10 6s2',
    },
    {
      symbol: 'Ho',
      name: 'Holmium',
      number: 67,
      atomic_mass: 164.93,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f11 6s2',
    },
    {
      symbol: 'Er',
      name: 'Erbium',
      number: 68,
      atomic_mass: 167.26,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f12 6s2',
    },
    {
      symbol: 'Tm',
      name: 'Thulium',
      number: 69,
      atomic_mass: 168.93,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f13 6s2',
    },
    {
      symbol: 'Yb',
      name: 'Ytterbium',
      number: 70,
      atomic_mass: 173.05,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f14 6s2',
    },
    {
      symbol: 'Lu',
      name: 'Lutetium',
      number: 71,
      atomic_mass: 174.97,
      category: 'lanthanide',
      electron_configuration: '[Xe] 4f14 5d1 6s2',
    },
  ],
  [
    {
      symbol: 'Th',
      name: 'Thorium',
      number: 90,
      atomic_mass: 232.04,
      category: 'actinide',
      electron_configuration: '[Rn] 6d2 7s2',
    },
    {
      symbol: 'Pa',
      name: 'Protactinium',
      number: 91,
      atomic_mass: 231.04,
      category: 'actinide',
      electron_configuration: '[Rn] 5f2 6d1 7s2',
    },
    {
      symbol: 'U',
      name: 'Uranium',
      number: 92,
      atomic_mass: 238.03,
      category: 'actinide',
      electron_configuration: '[Rn] 5f3 6d1 7s2',
    },
    {
      symbol: 'Np',
      name: 'Neptunium',
      number: 93,
      atomic_mass: 237,
      category: 'actinide',
      electron_configuration: '[Rn] 5f4 6d1 7s2',
    },
    {
      symbol: 'Pu',
      name: 'Plutonium',
      number: 94,
      atomic_mass: 244,
      category: 'actinide',
      electron_configuration: '[Rn] 5f6 7s2',
    },
    {
      symbol: 'Am',
      name: 'Americium',
      number: 95,
      atomic_mass: 243,
      category: 'actinide',
      electron_configuration: '[Rn] 5f7 7s2',
    },
    {
      symbol: 'Cm',
      name: 'Curium',
      number: 96,
      atomic_mass: 247,
      category: 'actinide',
      electron_configuration: '[Rn] 5f7 6d1 7s2',
    },
    {
      symbol: 'Bk',
      name: 'Berkelium',
      number: 97,
      atomic_mass: 247,
      category: 'actinide',
      electron_configuration: '[Rn] 5f9 7s2',
    },
    {
      symbol: 'Cf',
      name: 'Californium',
      number: 98,
      atomic_mass: 251,
      category: 'actinide',
      electron_configuration: '[Rn] 5f10 7s2',
    },
    {
      symbol: 'Es',
      name: 'Einsteinium',
      number: 99,
      atomic_mass: 252,
      category: 'actinide',
      electron_configuration: '[Rn] 5f11 7s2',
    },
    {
      symbol: 'Fm',
      name: 'Fermium',
      number: 100,
      atomic_mass: 257,
      category: 'actinide',
      electron_configuration: '[Rn] 5f12 7s2',
    },
    {
      symbol: 'Md',
      name: 'Mendelevium',
      number: 101,
      atomic_mass: 258,
      category: 'actinide',
      electron_configuration: '[Rn] 5f13 7s2',
    },
    {
      symbol: 'No',
      name: 'Nobelium',
      number: 102,
      atomic_mass: 259,
      category: 'actinide',
      electron_configuration: '[Rn] 5f14 7s2',
    },
    {
      symbol: 'Lr',
      name: 'Lawrencium',
      number: 103,
      atomic_mass: 266,
      category: 'actinide',
      electron_configuration: '[Rn] 5f14 6d1 7s2',
    },
  ],
];

export const ALL_ATOMS = [BOTTOM, LEFT_SIDE, RIGHT_SIDE];
